language: node_js
node_js:
- node
cache:
  directories:
  - functions/node_modules
stages:
- check_security
- build
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: check_security
    script: cd functions && npm audit
  - stage: build
    before_script:
    - cd functions && npm ci
    script: npm run build
  - stage: deploy
    script: skip
    before_deploy:
    - cd functions && npm ci && cd ..
    deploy:
      provider: firebase
      skip_cleanup: true
      token:
        secure: miu1muHR/S6l7fzywuDf/LX6YwFiQCfWiBVUitROB/UkmRyk93IEb42aSjRBc4YLvKVPEOjvy73M87mxVu/aHYRcWr39mbpT2q9zga0By8zsHV9euK5Q1fn4JmWDKdOuAC1SO1cXaOmLh8Y29HQz+othQpimIfMJl4mIxgQ35hARCQdFnC7whVXnjCr68S5OTY+8mN3YZOIENhcMsCjC5lZ4NUqqxEL+B341yURn6LyeIxjFyTSYJFSbIWHvvPkL6CPoonYWavlWQIQNgRpMLWGwgybdFVAbeZVUwlLw5x5d8NKHvMoccOiF1N/J4zczXln9HsgH/n6wQt79GoThZg2BvD7ArOeb6LZHSDrMXurZdTkL3ISKeuUUgdmzXO42KMqESc/4tXOQqGvs/DiNaBwHScpp1dHIDwKJdA8AW8t+/SdFltapNG0ENpNW3gu03gPH4HQ2srOQIse+zMhO4BAH2UGDyKt9Rvv9VTJg/2KLRueY0v7hSfW+xhoBo8vLE4SM0AYRw20pomzGEBwCVuoyTypIhBGWaE3ltbp92iW4mGiCBQacot//u29JI0VWp0ofQPRjsmH7RjwXqYpi79TuLftRV0qFmHkf05uRJylwZNIasDQAbbqbhP+XcwwxG/XEqfKifA12K9F9uOvH0kp84H+1rTtO8frMK6/qgNM=
