language: node_js
node_js:
  - "node"
cache:
  directories:
    - "functions/node_modules"
stages:
  - build
  - name: deploy
    if: branch = master
jobs:
  include:
  - stage: build
    before_script:
      - cd functions && npm ci
    script: npm run build
  - stage: deploy
    script: skip
    before_deploy:
      - cd functions && npm ci && cd ..
    deploy:
      provider: firebase
      skip_cleanup: true
      token:
        secure: E7F8qNjPYQM5dPqs2alWVxw0nE48lfwJyxdHkVhDedqYawCR37xFHUnXufosio72Zc3FBBstQap7cWc8s2IarZTAAJBQKhctPXcXN3z8+ROzIiZgf3pXWsLKrOwpvIaqKDzbRRSN+CN8T6Cx3FB3h7xjOVvfewWPw6U/IDJQt+mYPoaR6GxtpD0lnYP2HwTGwTET7HQYD5r4dlsCJqYHRflzEVLzF88HPPwmMePmMUyGe98/NRjLXmJZH6M1je4Or66nSqkInfMsDbcaZcNh+hh4YUwImRhK4PrI6cmC4VambdhW0S5M3wpvKQd0Tr2Ow/7HyNeNw+mKixbqK8vhrUGeS1kafuTiBdgU2DjjZoTK05R2gx5NWOC55b5+S4uF8Es+JdJ7w2ET4GecFT5+9rXQ7AmXgqt0iKZUuaT6OB9bwXVlcYqCWYQTtBxXoHtMKovUS9V92UCBPKZn9E/n/kV4lOrk5m+ZYQcgi7A9gmA5nIr3fKPWUnSwE7HVDlw5NaTjk3EVZgqP2kX0A/ijrAzQxICETUjhg4kqxH8yxDRr0R12aBrIBdpkf0T4AGjNoFSvy74a6XkqztH7/dy4MQ7rETp3GE9jf8JdfW+aK9YPoJbqn+/VWt8lzCDbxXffNsmXe+wszPRxcAQxz1taSxTwwpFzzahls4CygAt3Pik=
